#!/usr/bin/env sh
# Script assembled and exported by:
#     ___ ___  ___  ____ ____  ___ __ __
#    / __/ _ \/ _ |/ ___/ __/ / __/ // /
#   _\ \/ ___/ __ / /__/ _/_ _\ \/ _  /
#  /___/_/  /_/ |_\___/___(_)___/_//_/
#  version: 1.5.0 | https://space.sh
#
# Node: /run/

set -u  # Will not allow for unset variables being used.

daysUntilExpire="${daysUntilExpire:-20}"
certDir="${certDir:-/mnt/certs}"
certsList="${certsList:-/mnt/certs_list/certs.txt}"
SPACE_LOG_LEVEL="${SPACE_LOG_LEVEL:-4}"
SPACE_LOG_ENABLE_COLORS="${SPACE_LOG_ENABLE_COLORS:-1}"
SPACE_ASSERT_EXIT="${SPACE_ASSERT_EXIT:-0}"
SPACE_MUTE_EXIT="${SPACE_MUTE_EXIT:-0}"
SPACE_MUTE_EXIT_MESSAGE="${SPACE_MUTE_EXIT_MESSAGE:-0}"
RENEWER_RUN()
{
    local _SPACE_NAME="RENEWER_RUN"

    if [ -z "${daysUntilExpire}" ]; then
        PRINT "Missing env variable daysUntilExpire" "error" 0
        return 1
    fi

    if [ ! -d "${certDir}" ]; then
        PRINT "Cert dir does not exist: ${certDir}" "error" 0
        return 1
    fi

    if [ ! -f "${certsList}" ]; then
        PRINT "Certs list does not exist: ${certsList}" "error" 0
        return 1
    fi

    if ! command -v tar >/dev/null 2>&1; then
        PRINT "tar not installed" "error" 0
        return
    fi

    if ! command -v curl >/dev/null 2>&1; then
        PRINT "curl not installed" "error" 0
        return
    fi

    if ! command -v openssl >/dev/null 2>&1; then
        PRINT "openssl not installed" "error" 0
        return
    fi

    if ! command -v socat >/dev/null 2>&1; then
        PRINT "socat not installed" "error" 0
        return
    fi

    local secondsToLive="$((daysUntilExpire * 86400))"

    cd "${certDir}"

    _PERFORM "${certsList}" "${secondsToLive}"
}

PRINT()
{
    local color=''
    local header=''
    [ "${3:-1}" = 1 ] && {
        local _SPACE_NAME="${_SPACE_NAME:-anonymous}: ";
    } || {
        local _SPACE_NAME="";
    }

    case "${2:-info}" in
        error)
            if [ "${SPACE_LOG_LEVEL:-4}" -lt 1 ]; then return; fi
            header="[ERROR] "; color="\033[31m"
            ;;
        security)
            if [ "${SPACE_LOG_LEVEL:-4}" -lt 1 ]; then return; fi
            header="[SEC]   "; color="\033[35m"
            ;;
        warning)
            if [ "${SPACE_LOG_LEVEL:-4}" -lt 2 ]; then return; fi
            header="[WARN]  "; color="\033[33m"
            ;;
        ok)
            if [ "${SPACE_LOG_LEVEL:-4}" -lt 3 ]; then return; fi
            header="[OK]    "; color="\033[32m"
            ;;
        info)
            if [ "${SPACE_LOG_LEVEL:-4}" -lt 4 ]; then return; fi
            header="[INFO]  "; color="\033[37m"
            ;;
        debug)
            if [ "${SPACE_LOG_LEVEL:-4}" -lt 5 ]; then return; fi
            header="[DEBUG] "; color=""
            ;;
        *)
            return
            ;;
    esac
    if [ "${SPACE_LOG_ENABLE_COLORS}" = "1" ] && [ -t 2 ]; then
        printf "${color}%s%s%s\033[0m\n" "${header}" "${_SPACE_NAME}" "${1}" >&2
    else
        printf "%s%s%s\n" "${header}" "${_SPACE_NAME}" "${1}" >&2
    fi
}

_PERFORM()
{
    local _SPACE_NAME="_PERFORM"

    local certsList="${1}"
    shift

    local secondsToLive="${1}"
    shift

    local lines=
    if ! lines="$(_GET_CERTS "${certsList}" "${secondsToLive}")"; then
        return 1
    fi

    # Step through each cert, check connectivity and then issue a renewal to LE.
    local nl="
"
    local line=
    local certsIssued=0
    local domainsDone=""
    local anyFailure=0
    local issueFailure=0
    local ifs="${IFS}"
    local IFS="${nl}"
    for line in $lines; do
        IFS="${ifs}"
        local certFile="${line%%[ ]*}"
        local domains="${line#*[ ]}"
        local domain=
        local isOk=1
        PRINT "Performing connectivity probes for domains \"${domains}\", waiting..." "info" 0
        for domain in ${domains}; do
            if ! _CHECK_CONNECTIVITY "${domain}"; then
                isOk=0
                anyFailure=1
            fi
        done
        if [ "${isOk}" = "1" ]; then
            if _ISSUE_CERT "${certFile}" "${domains}"; then
                certsIssued="$((certsIssued+1))"
                domainsDone="${domains}${domainsDone:+ }${domainsDone}"
            else
                anyFailure=1
                issueFailure=1
            fi
        else
            PRINT "Will not renew certificate for domains: ${domains}" "error" 0
        fi
    done
    IFS="${ifs}"

    # Pack all certs into tar.gz file, if any was issued
    if [ "${certsIssued}" -gt 0 ]; then
        PRINT "${certsIssued} certs issued for domains: ${domainsDone}" "info" 0
    fi

    # We bundle cert on each invocation, regardless if any new ones were issued.
    # This to squash some logical fallacies when doing rearrangements in the certs list file.
    if ! _BUNDLE_CERTS "${certsList}"; then
        anyFailure=1
    fi

    # Always return error if any cert failed to renew, in this way this script will get rerun soon again to retry.
    if [ "${issueFailure}" = "1" ]; then
        # In this case we might have hit a rate limit.
        # Sleep some so we don't hammer the LE API with retries
        sleep 10
        return 1
    elif [ "${anyFailure}" = "1" ]; then
        # Sleep some so we don't hammer the LE API with retries
        sleep 10
        return 1
    fi
}

_GET_CERTS()
{
    local _SPACE_NAME="_GET_CERTS"

    local certsList="${1}"
    shift

    local secondsToLive="${1}"
    shift

    local domains=
    local hash=
    while IFS='' read -r domains || [ -n "${domains}" ]; do
        STRING_TRIM "domains"
        if [ "${domains#[#]}" != "${domains}" ]; then
            continue
        fi
        if [ -z "${domains}" ]; then
            continue
        fi
        STRING_HASH "${domains}" hash
        local certFile="${hash}.pem"
        local issue=1
        if [ "${secondsToLive}" -gt 0 ]; then
            if [ -f "${certFile}" ]; then
                # Check valid cert file
                if ! openssl x509 -in "${certFile}" -text -noout >/dev/null 2>&1; then
                    PRINT "Cert is invalid ${certFile}" "error" 0
                fi
                # Check valid date
                if openssl x509 -checkend "${secondsToLive}" -noout -in "${certFile}" >/dev/null; then
                    issue=0
                else
                    PRINT "Cert ${certFile} ($domains) has/is expiring" "info" 0
                fi
            fi
        fi
        if [ "${issue}" = "1" ]; then
            printf "%s %s\\n" "${certFile}" "${domains}"
        fi
    done <"${certsList}"
}

_CHECK_CONNECTIVITY()
{
    local _SPACE_NAME="_CHECK_CONNECTIVITY"
    local domain="${1}"
    shift

    local randomID="$(awk 'BEGIN{min=1;max=65535;srand(); print int(min+rand()*(max-min+1))}')"

    # Create listener which will spawn a process and return the random ID we have.
    socat TCP-LISTEN:8080,reuseaddr,fork exec:'sh -c "\"printf \\\"HTTP/1.1 200 OK\\\r\\\nContent-Length: '${#randomID}'\\\r\\\n\\\r\\\n'${randomID}'\\\"\""' &
    pid="$!"

    # TODO: we need to manage spam of this url.
    local content=
    content="$(curl -Ls "http://${domain}/.well-known/acme-challenge/probe")"

    kill "${pid}"

    if [ "${content}" = "${randomID}" ]; then
        return 0
    fi

    PRINT "Domain ${domain} does not connect to here. DNS malconfiguration? Skipping this cert" "error" 0
    return 1
}

_ISSUE_CERT()
{
    local _SPACE_NAME="_ISSUE_CERT"

    local certFile="${1}"
    shift

    local domains="${1}"
    shift

    PRINT "Update cert for domains: ${domains}" "info" 0

    local domains2=
    local domain=
    for domain in ${domains}; do
        domains2="${domains2} -d ${domain}"
    done

    if ! /acme.sh --issue --cert-home . --standalone ${domains2} --httpport 8080 --fullchain-file "${certFile}.tmp" --key-file "${certFile}.key" --force >/dev/null; then
        PRINT "Could not issue cert." "error" 0
        return 1
    fi

    cat "${certFile}.key" >> "${certFile}.tmp"
    rm "${certFile}.key"
    mv -f "${certFile}.tmp" "${certFile}"
    PRINT "Cert issued for ${domains}" "ok" 0
}

_BUNDLE_CERTS()
{
    local _SPACE_NAME="_BUNDLE_CERTS"

    local certsList="${1}"
    shift

    local lines=
    if ! lines="$(_GET_CERTS "${certsList}" "0")"; then
        return 1
    fi

    local nl="
"
    local line=
    printf "%s\\n" "I used to be The Astro Chicken. Now I'm simply a placeholder for empty tar archives..." >".astrochicken"
    local files=".astrochicken"
    local ifs="${IFS}"
    local IFS="${nl}"
    for line in $lines; do
        IFS="${ifs}"
        local certFile="${line%%[ ]*}"
        if [ -f "${certFile}" ]; then
            files="${files}${files:+ }${certFile}"
        fi
    done
    IFS="${ifs}"

    if ! tar czf "certs.tar.gz.tmp" ${files}; then
        PRINT "Could not tar certs" "error" 0
        return 1
    fi
    mv -f "certs.tar.gz.tmp" "certs.tar.gz"
}

STRING_HASH()
{
    local _SPACE_NAME="STRING_HASH"

    local __str="${1}"
    shift

    local __outvar="${1}"
    shift

    local SHASUMBIN=
    if command -v sha256sum >/dev/null; then
        SHASUMBIN="sha256sum"
    elif command -v shasum >/dev/null; then
        SHASUMBIN="shasum -a 256"
    fi

    if [ -z "${SHASUMBIN}" ]; then
        return 1
    fi

    local __hash=
    __hash=$(printf "%s\\n" "${__str}" |${SHASUMBIN}) || { return 1; }
    __hash="${__hash%%[ ]*}"
    eval "${__outvar}=\"\${__hash}\""
}

STRING_TRIM()
{
    local _SPACE_NAME="STRING_TRIM"

    # shellcheck disable=SC2034
    local __sopriv=
    eval "__sopriv=\"\${${1}}\""
    # shellcheck disable=SC2034
    local __tab="	"
    while true; do
        eval "${1}=\"\${$1#\"\${$1%%[! ]*}\"}\""
        eval "${1}=\"\${$1%\"\${$1##*[! ]}\"}\""
        eval "${1}=\"\${$1#\"\${$1%%[!\$__tab]*}\"}\""
        eval "${1}=\"\${$1%\"\${$1##*[!\$__tab]}\"}\""
        if eval "[ \"\${${1}}\" = \"\${__sopriv}\" ]"; then
            break
        fi
        eval "__sopriv=\"\${${1}}\""
    done
}

main()
{
    RENEWER_RUN 

    # Space will print exit status.
    local _status=$?
    if [ "${_status}" -ne "${SPACE_ASSERT_EXIT}" ]; then
        if [ "${SPACE_MUTE_EXIT_MESSAGE}" != "1" ] && [ "${SPACE_LOG_LEVEL}" -ge 1 ]; then
            [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ -t 2 ] && printf "\033[31m" >&2
            printf "%s\n" "[ERROR] Script exited with status $_status for node /run/" >&2
            [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ -t 2 ] && printf "\033[0m" >&2
        fi
        if [ "${SPACE_MUTE_EXIT}" != 1 ]; then
            return $((SPACE_ASSERT_EXIT == 0 ? _status : 1))
        fi
    elif [ "${SPACE_MUTE_EXIT_MESSAGE}" != "1" ] && [ "${SPACE_LOG_LEVEL}" -ge 5 ]; then
        [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ 5 -eq 3 ] && [ -t 2 ] && printf "\033[32m" >&2
        printf "%s\n" "[DEBUG] Script exited with success (status $_status) for node /run/" >&2
        [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ 5 -eq 3 ] && [ -t 2 ] && printf "\033[0m" >&2
        : # Important to reset status here.
    fi
}

main "$@"
